//
// This file is auto-generated by CMake.
//

#pragma once

#define PL_GIT_COMMIT_HASH_SHORT a23ee6aa0cbf
#define PL_GIT_COMMIT_HASH_LONG a23ee6aa0cbf1eafdd210f9118a1af81adf6c30b
#define PL_GIT_BRANCH_NAME "main"

