//
// This file is auto-generated by CMake.
//

#pragma once

#define PL_GIT_COMMIT_HASH_SHORT 97759154fd9d
#define PL_GIT_COMMIT_HASH_LONG 97759154fd9db9d8e35908a7bbde8d420316dfbb
#define PL_GIT_BRANCH_NAME "main"

